nasl_mesaj = [
    "I'm fine, thank you. Talking to you makes me feel even better.",
    "Great, thanks! It's a pleasure to chat with you.",
    "I'm doing quite well, thank you. How about you?",
    "I'm very well, thank you. How's your day going?",
    "I'm fine. Is there anything else you'd like to ask?",
    "I'm doing quite well, thank you. How's your day going?",
    "I'm doing very well, thank you. How about you?",
    "I'm fine. How can I assist you?",
    "I'm doing great, thank you. How's your day going?",
    "I'm doing quite well. How's your day going?",
    "I'm fine, thank you. Talking to you makes me feel even better.",
    "Great, thanks! It's a pleasure to chat with you.",
    "I'm doing quite well, thank you. How about you?",
    "I'm very well, thank you. How's your day going?",
    "I'm fine. Is there anything else you'd like to ask?",
    "I'm doing quite well, thank you. How's your day going?",
    "I'm doing very well, thank you. How about you?",
    "I'm fine. How can I assist you?",
    "I'm doing great, thank you. How's your day going?",
    "I'm doing quite well. How's your day going?",
    "I'm fine, thank you. Talking to you makes me feel even better.",
    "Great, thanks! It's a pleasure to chat with you.",
    "I'm doing quite well, thank you. How about you?",
    "I'm very well, thank you. How's your day going?"
]


nbr_mesaj = [
        "It's going well, thank you. It's nice talking to you.",
        "Great, thanks! I hope your day is going well too.",
        "I'm doing quite well, thank you. How's your day going?",
        "I'm very well, thank you. How's your day going?",
        "It's going well. Is there anything you'd like to ask?",
        "I'm doing quite well, thank you. How's your day going?",
        "I'm doing very well, thank you. How about you?",
        "It's going well. How can I assist you?",
        "I'm doing great, thank you. How's your day going?",
        "I'm doing quite well. How about you?",
        "It's going well, thank you. It's nice talking to you.",
        "Great, thanks! I hope your day is going well too.",
        "I'm doing quite well, thank you. How's your day going?",
        "I'm very well, thank you. How's your day going?",
        "It's going well. Is there anything you'd like to ask?",
        "I'm doing quite well, thank you. How's your day going?",
        "I'm doing very well, thank you. How about you?",
        "It's going well. How can I assist you?",
        "I'm doing great, thank you. How's your day going?",
        "I'm doing quite well. How about you?",
        "It's going well, thank you. It's nice talking to you.",
        "Great, thanks! I hope your day is going well too.",
        "I'm doing quite well, thank you. How's your day going?",
        "I'm very well, thank you. How's your day going?",
        "It's going well. Is there anything you'd like to ask?"
]

espiri_mesaj = [
    "Temel went to France and saw a sign that said 'France.' He exclaimed, 'Wow! Did SABANCI buy this place too?",
    "The shortest way to make your dreams come true is to wake up.. (S.M. Poker)",
    "Edison invented electricity, but we're the ones paying the bills.",
    "Do you want to earn 200 million on the moon? Then go to the moon.",
    "There are two types of people: those who split down the middle.",
    "What matters in a woman is the beauty of her soul. The ideal body measurements for a good soul are 36-24-36.",
    "You know how the waves wash away the writings on the shore, and how the wind tosses the white seagulls back and forth? Well, may those seagulls poop on your head.",
    "I demand my right. Hakki’s wife.",
    "An uncooked hamburger is called a HAM-BURGER.",
    "The economy is stuck. Let's RESET it, please.",
    "My youth was causing me pain, so I had it removed with surgery.",
    "I named my son MAFIA, now I’m a MAFIA BOSS.",
    "Oh, Azrael, you really kill people.",
    "Don't worry, you'll be the last one laughing. Because you always understand things late.",
    "Who would believe what you say? Of course, Kadir İNANIR would.",
    "The 40 years of respect for coffee drunk in 1961 has expired. Take note!",
    "Oh, rising new generation! Get down!",
    "They said 'your money or your honor'; I swear I didn't give them a penny.",
    "Let me be a slave for a thousand years to the one who loves me for who I am!",
    "Grapes may turn dark by looking at each other, but no one who sleeps with a blind person wakes up cross-eyed.",
    "Humans were invented. Ecology got messed up.",
    "If I had studied, I would have been a decent man. Now I'm a billionaire!",
    "Some parasites live in the intestines, even if we don't shout about it...",
    "I ran after my ex, passed her, and she was shocked.",
    "The man froze, and so did his wife.",
    "What is an elevator? Let me tell you.",
    "I was driving the truck, Leonardo da Vinci.",
    "I had the house painted white, the car by Cem Yılmaz.",
    "Where does this road lead? I like it.",
    "I bought a pineapple at the market, it was spoiled... :D",
    "What happens if the energy a substance provides isn't equal to the square of its mass in the universe?",
    "One guy burned, his wife was straight.",
    "One guy was gay, then he fell.",
    "The neighbor's kid asked if the computer was working? I said 'No, it's a housewife', the kid ran away from home.",
    "One guy fell, his wife was a dream.",
    "One guy laughed, they planted him in the garden.",
    "One guy loosened up, his wife was a boat.",
    "Who are you? I'm Migros.",
    "I went to the payment point, said 'P', and left.",
    "If the world is round, how do some people turn the corner?",
    "If you want to be noticed, eat garlic.",
    "A madman asked another madman what love is, the madman laughed and said 'that's why I went mad'.",
    "Even if I die, I won't eat grief, it gives me gas.",
    "We never found a girl to match our cause, nor were we simple enough for a girl; a girl should be like Istanbul, hard to conquer, with a single conqueror!!!!!",
    "Oh Turkish Woman!! Your first duty is to wash dishes, do laundry, and take care of your husband.",
    "What did God say while creating the second black man? 'Oops, we burned this one too!!'",
    "I know something as well as my name, and that's my last name.",
    "This is the last plum, there is no other plum.",
    "What do you call a meal eaten by men? Menemen.",
    "Our love was like two bespectacled people trying to kiss, but we couldn't figure out to take off the glasses.",
    "My wife is so diligent, she irons out my brain.",
    "Who said you can't cross at a red light? The late one used to cross.",
    "Dear future, I'm going to the post office. If you arrive and I'm not home, the key is under the mat.",
    "Brother, do they call side-by-side stations, side by side?",
    "When we exchange our money, let's hope it doesn't leave a stain in our pockets.",
    "It's snowing outside, let's not eat it raw or our stomachs will get upset.",
    "Why is our caravan black, is it a caravan?",
    "What's a hair removal cream? A hair remover.",
    "Take these shoes, and run away with them.",
    "Ratio is beautiful. Stop saying 'this and that' is beautiful, it's rude.",
    "How beautiful the éclairs are, would you like to add something too?",
    "I'm not coming to the water slide, I don't like water jokes.",
    "We'll conduct our experiment by experimenting.",
    "These are temporary, they'll pass through like this.",
    "Check the coals, still... on my coals.",
    "We sat close to Dora so she wouldn't feel out of place.",
    "Hitler, these are the best musics of this vein.",
    "We made a mistake by choosing a rainy day to visit Hatay.",
    "This is detergent skip. It says skip while watching here.",
    "Kilo shop, what are we doing, gaining weight inside?",
    "If you had fallen, you would have fallen in Hatay.",
    "The bell rings every hour on the hour.",
    "Which cover isn't used on the table? - Vegetation cover",
    "Grapes darken by looking at each other. So how does the first grape darken? - With the front camera",
    "What do you call a bug with diarrhea? - A cricket",
    "What do you call 10 in the toilet? - A siphon",
    "What do you call a small puddle? - A small water (su-cuk)",
    "Is the chair empty? - No, Arçelik",
    "The partridge joined the army, what happened? - It became a male (Er-keklik)",
    "Which Ceren cooks the best meals? - A pot (Ten’ceren)",
    "What do you call a baby who doesn't want to wear socks? - Anti'patik",
    "What do you call a man in red? - An officer (Al’bay)",
    "What do you call an uncooked burger? - A raw burger (Ham’burger)",
    "How does the wind blow in an ancient city? - As an ancient wind",
    "What do you call a male horse? - A stallion (Bay’at)",
    "Who does everyone take their hat off to? - A barber",
    "How do hedgehogs sleep? - On edge",
    "Why don't frogs wear swimsuits? - Because they might come off when they jump.",
    "What's the cleanest bug? - A cockroach (Hamamböceği)",
    "What's chewed but not swallowed? - A rule",
    "Which container can't hold water? - A shoe",
    "What did one koala say to the other? - I'll go, you koala.",
    "You should fear not the snake, but the unyielding.",
    "A man got angry, they came to ask for his hand.",
    "A hijacker was going to hijack a plane, but he couldn't. Because he missed his flight.",
    "One guy's house burned down, his rooms were straight.",
    "One guy laughed, they put him in a vase.",
    "I hailed a taxi yesterday, it's still spinning.",
    "One flower wilted, the other is still standing.",
    "Rain fell, snow turned into cheese.",
    "One guy loved riding horses. As soon as he got on, he fainted.",
    "Fish sandwich costs 5 liras. Let's plant some fish!",
    "They said there would be a ten-minute break in the cinema. I called, they didn't answer.",
    "One guy's eyes filled up, his nose was a taxi.",
    "One guy appeared on TV, he never came down.",
    "How beautiful the éclairs are, would you like to add something too?",
    "I'm not coming to the water slide, I don't like water jokes.",
    "We'll conduct our experiment by experimenting.",
    "These are temporary, they'll pass through like this.",
    "Check the coals, still... on my coals.",
    "We sat close to Dora so she wouldn't feel out of place.",
    "Hitler, these are the best musics of this vein.",
    "We made a mistake by choosing a rainy day to visit Hatay.",
    "This is detergent skip. It says skip while watching here.",
    "Kilo shop, what are we doing, gaining weight inside?",
    "If you had fallen, you would have fallen in Hatay.",
    "The bell rings every hour on the hour.",
    "Which cover isn't used on the table? - Vegetation cover",
    "Grapes darken by looking at each other. So how does the first grape darken? - With the front camera",
    "What do you call a bug with diarrhea? - A cricket",
    "What do you call 10 in the toilet? - A siphon",
    "What do you call a small puddle? - A small water (su-cuk)",
    "Is the chair empty? - No, Arçelik",
    "The partridge joined the army, what happened? - It became a male (Er-keklik)",
    "Which Ceren cooks the best meals? - A pot (Ten’ceren)",
    "What do you call a baby who doesn't want to wear socks? - Anti'patik",
    "What do you call a man in red? - An officer (Al’bay)",
    "What do you call an uncooked burger? - A raw burger (Ham’burger)",
    "How does the wind blow in an ancient city? - As an ancient wind",
    "What do you call a male horse? - A stallion (Bay’at)",
    "Who does everyone take their hat off to? - A barber",
    "How do hedgehogs sleep? - On edge",
    "Why don't frogs wear swimsuits? - Because they might come off when they jump.",
    "What's the cleanest bug? - A cockroach (Hamamböceği)",
    "What's chewed but not swallowed? - A rule",
    "Which container can't hold water? - A shoe",
    "What did one koala say to the other? - I'll go, you koala.",
    "You should fear not the snake, but the unyielding.",
    "A man got angry, they came to ask for his hand.",
    "A hijacker was going to hijack a plane, but he couldn't. Because he missed his flight.",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "Why don't scientists trust atoms? Because they make up everything!",
    "How does a penguin build its house? Igloos it together!",
    "Why did the math book look sad? Because it had too many problems.",
    "Why did the bicycle fall over? Because it was two-tired.",
    "What do you get when you cross a snowman and a vampire? Frostbite!",
    "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
    "What do you call fake spaghetti? An impasta!",
    "Why did the tomato turn red? Because it saw the salad dressing!",
    "How do you organize a space party? You planet!",
    "What do you call cheese that isn't yours? Nacho cheese!",
    "Why don’t skeletons fight each other? They don’t have the guts.",
    "What did one wall say to the other wall? I'll meet you at the corner!",
    "Why did the coffee file a police report? It got mugged.",
    "What did the grape do when it got stepped on? Nothing but let out a little wine!",
    "Why did the computer go to the doctor? It had a virus.",
    "What do you call a bear with no teeth? A gummy bear!",
    "Why don’t scientists trust atoms? Because they make up everything!",
    "What did the zero say to the eight? Nice belt!",
    "Why did the chicken join a band? Because it had the drumsticks.",
    "How does a scientist freshen her breath? With experi-mints!",
    "Why can't your nose be 12 inches long? Because then it would be a foot!",
    "What do you call an alligator in a vest? An investigator!",
    "Why don’t programmers like nature? It has too many bugs.",
    "Why did the cookie go to the hospital? Because it felt crummy.",
    "What do you call a sleeping bull? A bulldozer!" 
]

laf_mesaj = [
    "Some people should be thrown out of the window from the perspective they view life.",
    "Stop! Let me take out my brain so we can talk on equal terms.",
    "Darling, your character fell to the ground. Pick it up from there.",
    "I heard it bothered you. Nice place, I went there too!",
    "Haven't you accepted yet the sins you thought were virtues?",
    "Don't think I've forgotten you, I just remember you as much as you're worth.",
    "Today, I won't put in any words. I made tea; come, drink, and see humanity.",
    "We said, 'Don't be missing.' Now you are becoming too many. What's the matter?",
    "I know how to expend people well. Just be broken.",
    "When my patience runs out, there is no one I can't erase from my life.",
    "Don't run after anyone because those who love walk side by side.",
    "I kept you on top, did you not understand? Are you comfortable underfoot?",
    "You’re as hard as a rock, but an OKEY piece… you’re being passed around, not even aware.",
    "We're dealing with people who don't even notice the apartment light.",
    "Your looks are Tarlabaşı, but your ego is like Nişantaşı.",
    "I would have made a man out of you, but you’ve already become my dog, so what's the point?",
    "I collect broken things like you in my piggy bank for future investment. If I'm in a tight spot, I spend them without a second thought.",
    "To those who come only when needed, is it called a friend or a scoundrel or a pretender?",
    "I thought of you, and you left. Who knows where you’re going again.",
    "Some people wipe their tears, some people wipe the one who made them cry...",
    "I know people who would take time to be human if I asked them for two minutes.",
    "If what I say seems heavy, it means my words were not empty.",
    "By believing in you, I might lose ONE DAY, but you will lose a lifetime with your characterless ways.",
    "Those who leave think that those who stay cry every day. Songs are left unfinished because you turned off the radio.",
    "Please don’t pretend to be human, it doesn’t suit you.",
    "Those who should be with me are already here; those who leave are of no concern.",
    "I was about to make you kneel, but they said poetry isn’t written for a two-syllable name, for a three-penny woman…",
    "When skirts burn without a master, all the dogs return to their owners.",
    "At least I know my killer. But one day, in a heart where you are not loved, you'll go to 'who hit me'...",
    "Don’t put a promise you can’t keep on your lips, love you can’t give in your heart, or a person you can’t make happy in your life.",
    "Those who think they have a debt should not think the books are closed. I’m writing them down one by one. Good or bad, debts will be paid someday...",
    "Don’t make mistakes with someone who has no tolerance left. When erasing, they think about themselves, not you.",
    "Take only as much food as you can eat, and as many people as you can love into your life. There’s no need for waste.",
    "Don’t engage in tasks you can’t account for! They don’t do the dishes on the other side.",
    "Darling, look! If you have a problem, you know, I don’t care at all.",
    "I can’t sleep without looking at your picture every night; I’ll spit if I must.",
    "When you annoy me, I want to beat you up and say, ‘Sorry! I got carried away.’",
    "You know, if your presence is ‘fifi’ and your absence is ‘tın’! My presence is ‘event’, and my absence ‘hurts’..!",
    "You’ve fed your ego so much that your character is starving.",
    "Shame on your shadow too! It thought you were a person and followed you.",
    "Am I the ‘foundation for fighting backwardness’?",
    "They say germs die when it snows. Are you okay?",
    "If I made your name my password, it would say insufficient characters and still be talking.",
    "Some people light up the room when they enter, others when they leave…",
    "I would sit down and tell you about honor, but listening to something lost is heavy for a person.",
    "Today, I won’t put in any words. I made tea; come, drink, and see humanity.",
    "We didn’t exist with anyone’s presence. We won’t cease to exist with their absence.",
    "If you’re giving advice and there’s not enough left for you, I don’t want you to take risks for me.",
    "True friends show up in tough times. Turn off the lights, I’ll count my friends!",
    "Those who should be with me are already here, and those who leave, who cares?",
    "I collect broken things like you in my piggy bank for future investment. If I'm in a tight spot, I spend them without a second thought.",
    "If your feelings were as honorable as you talk, your honor wouldn’t be worth two cents.",
    "You said you could take people like him out of your pocket. Listen! I put people like you in my rosary and pull them out, repenting.",
    "For those looking for an experienced sales person, I give the names of my old friends.",
    "We are the captains of the ship we walk on land, what oar are you on?",
    "If people knew themselves first, then their limits, and finally what they wanted, there wouldn’t be any problems.",
    "Those who act like angels in front of me, think they’re digging a pit behind my back. They should never forget, I’m struggling with the devil within them.",
    "We are a generation that learned to count from beans. We know well whom we will count as beans.",
    "If one time came for these people, they wouldn’t sell themselves so cheaply.",
    "People like you can only satisfy their water needs by licking their spit. What can you do…",
    "I love drawing with charcoal. Because I still haven’t figured out what color anyone is.",
    "When buying a saddle for a donkey, what is thought of is not asked, it is measured. Don’t make me measure your worth!",
    "I love self-admiring people. It’s a privilege to like something that no one else likes.",
    "You've fallen so low that you're hitting rock bottom. Pick yourself up and maybe we can talk again.",
    "Don't worry about the days we haven't seen each other; I've already forgotten you.",
    "I suggest you pay attention because the only thing that attracts your attention is your own ego.",
    "Your problems aren't even worth as much as you think; until you face real issues, they're meaningless.",
    "Your conversations often overflow their container; perhaps one day we can see if you can fit inside yourself.",
    "People often forget their worth over time, but the value gap between us remains permanent.",
    "Life is short, so there's no time for unnecessary arguments.",
    "You don't have to carry anyone on your back; those who can carry their own weight will be by your side.",
    "Sometimes, just giving someone a bit of time is enough to see how empty they are.",
    "Whenever I need you, I hope you'll always be there, so you can show your true friendship.",
    "Constantly praising yourself doesn't affect how others see you. You should find a way to become a better person.",
    "Everything is temporary, so avoid wasting your life on unnecessary things.",
    "Those who know me understand what true friendship is. This could be a learning opportunity for you.",
    "If you see yourself as important, you should also pay attention to how others see you.",
    "True friendship shows up in tough times. Those who are with us in dark days are valuable.",
    "The value of the time I spend with you is measured by the interest and sincerity you show.",
    "Sometimes the best solution is to stay silent and let events unfold on their own.",
    "You should find someone who will tell you the most important things in life, as valuable information can come from the most unexpected places.",
    "Sharing your thoughts helps us understand you, but you shouldn't forget that your actions are equally important."
]

sarki_mesaj = [
        "Billie Jean - Michael Jackson",
        "Shape of You - Ed Sheeran",
        "Smells Like Teen Spirit - Nirvana",
        "I Wanna Dance with Somebody - Whitney Houston",
        "Blinding Lights - The Weeknd",
        "Wannabe - Spice Girls",
        "Umbrella - Rihanna ft. Jay-Z",
        "Like a Virgin - Madonna",
        "Waterfalls - TLC",
        "Hot in Herre - Nelly",
        "Dancing Queen - ABBA",
        "Teenage Dream - Katy Perry",
        "Rolling in the Deep - Adele",
        "Sweet Child O' Mine - Guns N' Roses",
        "Levitating - Dua Lipa",
        "My Heart Will Go On - Celine Dion",
        "Poker Face - Lady Gaga",
        "I Want It That Way - Backstreet Boys",
        "Happier - Marshmello ft. Bastille",
        "Single Ladies (Put a Ring on It) - Beyoncé",
        "Despacito - Luis Fonsi ft. Daddy Yankee",
        "Just Dance - Lady Gaga",
        "Good 4 U - Olivia Rodrigo",
        "Kiss Me More - Doja Cat ft. SZA",
        "Bad Romance - Lady Gaga",
        "No Scrubs - TLC",
        "Shivers - Ed Sheeran",
        "Bad Guy - Billie Eilish",
        "Old Town Road - Lil Nas X ft. Billy Ray Cyrus",
        "Genie in a Bottle - Christina Aguilera",
        "Levitating - Dua Lipa",
        "Stay - The Kid LAROI & Justin Bieber",
        "Watermelon Sugar - Harry Styles",
        "Tik Tok - Kesha",
        "I Want to Break Free - Queen",
        "Peaches - Justin Bieber ft. Daniel Caesar & Giveon",
        "All Star - Smash Mouth",
        "Montero (Call Me By Your Name) - Lil Nas X",
        "Good 4 U - Olivia Rodrigo",
        "Crazy in Love - Beyoncé ft. Jay-Z",
        "Drivers License - Olivia Rodrigo",
        "Shut Up and Dance - WALK THE MOON",
        "Levitating - Dua Lipa",
        "Save Your Tears - The Weeknd",
        "Blame It on the Boogie - The Jacksons",
        "Gangnam Style - PSY",
        "Havana - Camila Cabello ft. Young Thug",
        "Toxic - Britney Spears",
        "Can’t Stop the Feeling! - Justin Timberlake",
        "Hallelujah - Leonard Cohen",
        "I Gotta Feeling - The Black Eyed Peas",
        "Rolling in the Deep - Adele",
        "Call Me Maybe - Carly Rae Jepsen",
        "Radioactive - Imagine Dragons",
        "Sorry - Justin Bieber",
        "Uptown Funk - Mark Ronson ft. Bruno Mars",
        "Happy - Pharrell Williams",
        "Rude - MAGIC!",
        "Someone Like You - Adele",
        "Just the Way You Are - Bruno Mars",
        "Shape of You - Ed Sheeran",
        "Sucker - Jonas Brothers",
        "Perfect - Ed Sheeran",
        "The Middle - Zedd, Maren Morris, Grey",
        "Bad Liar - Imagine Dragons",
        "Dusk Till Dawn - Zayn ft. Sia",
        "Roar - Katy Perry",
        "Royals - Lorde",
        "Sledgehammer - Peter Gabriel",
        "I’m Still Standing - Elton John",
        "Don't Let Me Down - The Chainsmokers ft. Daya",
        "Dance Monkey - Tones and I",
        "The Nights - Avicii",
        "A Thousand Years - Christina Perri",
        "Radioactive - Imagine Dragons",
        "Shallow - Lady Gaga & Bradley Cooper",
        "High Hopes - Panic! At The Disco",
        "Circles - Post Malone",
        "God's Plan - Drake",
        "Lose Yourself - Eminem"
]



rizz_mesaj = [
    "Are you a magician? Because whenever I look at you, everyone else disappears!",
    "I'm not a photographer, but I can picture us together.",
    "Do I know you? Because you look just like my next girlfriend/boyfriend.",
    "Do you know what my shirt is made of? Boyfriend material.",
    "They say fairy chimneys are the happiest place on earth. Apparently, no one has stood next to you.",
    "For some reason, I was feeling a bit down today. But things changed when you arrived.",
    "Are you religious? Because you’re the answer to all my prayers.",
    "It looks like I’ve lost my phone number. Can I have yours?",
    "I’m lost. Can you give me directions to your heart?",
    "Is there a parking ticket? Because you’ve got 'fine' written all over you.",
    "Are you sure you’re not tired? You’ve been running through my mind all day.",
    "Is there an airport nearby, or is it my heart taking off?",
    "Was your father a boxer? Because I’m knockout by you.",
    "I was wondering if you had an extra heart. Mine was stolen.",
    "Can you hold my arm and tell my friends that an angel just touched me?",
    "There’s only one thing I’d change about you, and that’s your last name.",
    "Aside from being sexy, what do you do for a living?",
    "Hi, how was heaven when you left it?",
    "Do you believe in love at first sight or should I walk by again?",
    "Is your dad a terrorist? Because you’re the bomb.",
    "Did the sun come out, or did you just smile at me?",
    "If I’m wrong, kiss me, but dinosaurs are still real, right?",
    "You’re beautiful and I’m pretty sweet. We’d be quite the sweet pair.",
    "If nothing lasts forever, will you be my nothing?",
    "Did it hurt? When you fell from heaven?",
    "Can I follow you home? Because my parents always told me to follow my dreams.",
    "Is your name Google? Because you have everything I’ve been searching for.",
    "Are you from Tennessee? Because you’re the only ten I see!",
    "Hi, I’m a thief, and I’m here to steal your heart.",
    "I may not be a genie, but I can make your dreams come true.",
    "There must be something wrong with my eyes, I can’t take them off you.",
    "Excuse me, were you talking to me? [No] Then please start.",
    "Was your dad an alien? Because there’s no other like you on Earth!",
    "Was your dad a thief? Because someone stole the stars from the sky and put them in your eyes.",
    "Do you have a pen? Because I want to erase your past and write our future.",
    "Hi. Do you have a boyfriend?",
    "I must be in a museum, because you’re truly a work of art.",
    "Am I a phone charger? Because I’d die without you.",
    "Can you take me to the doctor? Because I just broke my leg falling for you.",
    "You remind me of a magnet, because you’re attracting me to you!",
    "I’m not a mathematician, but I’m good with numbers. See, give me yours and I’ll show you what I can do with it.",
    "Didn’t I see you on the cover of Vogue?",
    "Someone call the cops, because looking this good should be illegal!",
    "Sorry, but you owe me a drink. [Why?] Because when I looked at you, I dropped mine.",
    "You must be a broom, because you just swept me off my feet.",
    "Am I feeling wrong, or is it just hot in here, or is it just you?",
    "You must be tired. You’ve been running through my mind all day.",
    "Hey Özge, is that you? Sorry, you look a lot like my friend Özge.",
    "You’re at least as amazing as I am.",
    "Are you a model? If not, you definitely should be.",
    "If I could rearrange the alphabet, I’d put U and I together.",
    "I’d even share my Ruffles with you. How about it, will you share some chips with me?",
    "Do you believe in love at first sight, or should I walk by again?",
    "Excuse me, didn’t we go to different schools when we were little? We have so much in common, don’t we?",
    "I’m new in town, so I’m a stranger here. Could you give me directions to your place?",
    "Was your mom or dad an alien? Because there’s nothing like you on this Earth.",
    "I seem to have forgotten my phone number. Can I borrow yours?",
    "- Did you hear that?\n- What sound?\n- How could you not? My heart just broke.",
    "Wouldn't our chocolate babies look great on a wedding cake?",
    "Oh my God, those shoulder bones, I thought they were a pair of wings.",
    "Was your dad a thief? If not, where did he find these diamonds that are in your eyes?",
    "What if your parents hadn't met? I would be the most unhappy person in the world.",
    "Can you give me directions to your heart?",
    "Today is February 1, 2003, at 12:36. I need to remember the day and time we met...",
    "Hi! You were amazing in the last episode of the series, can I get your autograph?",
    "This beauty can't be real, I must be dreaming. Could you give me a pinch?",
    "Seeing you took my breath away. I hope you know how to perform artificial respiration.",
    "Did you step on bread or something? God made you a stone.",
    "Is your name Google? Because you have everything I’ve been searching for.",
    "You’re driving me crazy, speeding up my heart. My mind stays with you, but could you enter my heart?",
    "They can’t erase from my heart, neither your name nor you...",
    "You and I; what a perfect match for a sentence.",
    "Everything can happen, but my heart can’t be without you.",
    "Writing poems for you is not my place. Your existence is already a poem!",
    "You reflect the beauty of your heart to me, my love.",
    "I don’t know which small good deed of mine you’re the big reward for.",
    "Stay as I loved you. Changing is only for seasons...",
    "From the ‘coffee’ in your eyes, add to my life, and let me stay ‘with you’ for the sake of forty years!",
    "They asked what you are to me. I said, from afar, you are the one I burn for.",
    "Your eyes... The most beautiful view of my heart. The one I never get tired of loving and watching.",
    "I’ve written countless poems for you, but told no one. I’ve kept them in my chest.",
    "You smile so beautifully that I say, ‘This is enough for me to have lived…’",
    "I’m scared that others will see what I see in you.",
    "Stay as I loved you. Changing is only for seasons...",
    "I don’t know which small good deed of mine you’re the big reward for.",
    "You’re so beautiful that I can’t look at your face. My hands are trembling, I can’t hold yours. I’m so attached that I can’t stay without you.",
    "While your presence is not enough for me, I have to console myself with your absence! Either take away what’s left of me, or come and complete my missing side…",
    "In my lonely life, I always applauded those who loved. Now that I’ve found you, I thank God for my loneliness.",
    "I wish you were here right now… Right at this moment… I wish I’d cross your mind right now… Right at this moment…",
    "Until your soul dripped like a warm breeze on mine, what should I do in this body? Love is you, longing is you, and I am you...",
    "You are the abyss I look into. You are the one I added as a lifetime to my life. You are the one I stamped on my chest.",
    "Today I decided to do something different from usual, but it didn’t work. I fell in love with you repeatedly and thought about you.",
    "Until your soul dripped like a warm breeze on mine, what should I do in this body? Love is you, longing is you, and I am you...",
    "Today I decided to do something different from usual, but it didn’t work. I fell in love with you repeatedly and thought about you.",
    "What a skillful thief your magical eyes are. I never knew when you stole my heart.",
    "If I couldn’t see your eyes every morning of every day, I swear living wouldn’t be worth it.",
    "I have a symmetry obsession, you know… Your heart must be opposite mine, and your eyes must face mine.",
    "The only thing left is my heart. I can’t even claim it anymore! Look, it has taken off and gone to you.",
    "The poems I wrote without my eyes meeting yours are melancholy. Let them not touch, I’m content with it, my dear.",
    "Today I decided to do something different from usual, but it didn’t work. I fell in love with you repeatedly and thought about you.",
    "What a skillful thief your magical eyes are. I never knew when you stole my heart.",
    "If I couldn’t see your eyes every morning of every day, I swear living wouldn’t be worth it.",
    "I have a symmetry obsession, you know… Your heart must be opposite mine, and your eyes must face mine.",
    "The only thing left is my heart. I can’t even claim it anymore! Look, it has taken off and gone to you.",
    "The poems I wrote without my eyes meeting yours are melancholy. Let them not touch, I’m content with it, my dear.",
    "I’ll chase you until you’re tired, and then you’ll accept the love I have for you.",
    "If I hold your hand and look into your eyes, will you be my last love whom I shout ‘I love you’?",
    "One hand holding a book, one hand holding coffee, and in my mind, you.",
    "I don’t have a debt for yesterday, today, and tomorrow’s Romantic Quotes… I know you are a gift to my life..."
]


fal_mesaj = [
    "The stars are aligned in your favor today. Embrace new opportunities with open arms.",
    "A change is coming your way. It will bring growth and new perspectives. Stay open-minded.",
    "You may encounter challenges today, but your resilience will guide you through. Trust your instincts.",
    "Someone from your past may reappear in your life. Reflect on the lessons they brought you.",
    "A pleasant surprise awaits you in the near future. Keep an eye out for unexpected blessings.",
    "Your hard work is about to pay off. Continue with determination and success will follow.",
    "Take time to nurture your relationships today. Genuine connections will bring you joy.",
    "A new adventure is on the horizon. Embrace it with enthusiasm and it will lead to personal growth.",
    "You will find clarity in a situation that has been troubling you. Trust that solutions are coming.",
    "Financial gains are likely if you make wise decisions today. Stay prudent with your resources.",
    "Your creativity will shine brightly today. Use it to solve problems and achieve your goals.",
    "You may need to make a difficult decision soon. Weigh your options carefully and trust your intuition.",
    "Your health and well-being are paramount. Take time for self-care and listen to your body.",
    "An unexpected opportunity for learning will present itself. Be ready to expand your knowledge.",
    "Emotional balance is key today. Seek harmony in your relationships and inner self.",
    "The universe is encouraging you to take a leap of faith. Trust in your abilities and take the risk.",
    "You might find yourself reflecting on past choices. Use this time to make positive changes.",
    "Someone will seek your advice today. Your wisdom will be appreciated and could lead to new connections.",
    "A moment of relaxation will help you recharge. Take a break and indulge in some well-deserved rest.",
    "Your efforts to improve a certain area of your life are about to show results. Keep going.",
    "You might feel a surge of inspiration today. Channel it into your projects and watch them flourish.",
    "Be mindful of your surroundings. Small details will reveal important insights.",
    "Your social circle will bring joy and support. Spend quality time with those who uplift you.",
    "A message from a loved one will bring comfort and reassurance. Pay attention to their words.",
    "Your patience will be rewarded soon. Trust that things are falling into place as they should.",
    "An important conversation is on the horizon. Approach it with honesty and openness.",
    "You will experience a boost in confidence today. Use it to tackle challenges and pursue your goals.",
    "A chance encounter could lead to a new opportunity. Stay alert and be ready to seize it.",
    "Your financial situation is looking positive. Consider making investments or saving for future goals.",
    "A sense of adventure will inspire you to explore new possibilities. Embrace the excitement.",
    "You may need to let go of something or someone that no longer serves you. Embrace the change with grace.",
    "A personal project or goal will see progress today. Continue your efforts and celebrate small victories.",
    "You will find comfort in familiar routines. Embrace them as a source of stability and peace.",
    "A sense of clarity will help you navigate through confusion. Trust in your ability to make wise decisions.",
    "You may experience a burst of energy. Use it to complete tasks and achieve your objectives.",
    "A moment of introspection will provide valuable insights. Take time to reflect and grow.",
    "You will receive recognition for your hard work. Enjoy the acknowledgment and use it as motivation.",
    "A new connection or relationship may form today. Be open to meeting new people and forming bonds.",
    "Your intuition will be strong. Trust your gut feelings and let them guide you in your decisions.",
    "You may encounter a minor obstacle. Approach it with patience and resourcefulness to overcome it.",
    "A creative project or idea will come to fruition. Celebrate your achievements and keep innovating.",
    "You will find joy in simple pleasures today. Take time to appreciate the little things in life.",
    "An opportunity for personal growth is on the horizon. Embrace it with enthusiasm and an open mind.",
    "Your ability to communicate effectively will bring positive results. Express yourself clearly and confidently.",
    "A surprise gesture of kindness will brighten your day. Appreciate and reciprocate the generosity.",
    "You may experience a sense of harmony in your personal and professional life. Enjoy the balance.",
    "A moment of peace and tranquility will rejuvenate you. Seek out quiet moments for reflection.",
    "Your positive attitude will attract success. Maintain your optimism and watch opportunities unfold.",
    "You will find support from unexpected sources. Be open to receiving help and guidance from others.",
    "A personal achievement will bring you satisfaction. Take pride in your accomplishments and celebrate.",
    "You may need to make adjustments to your plans. Flexibility will help you navigate any changes smoothly.",
    "Your energy levels will be high. Use this vitality to pursue your passions and tackle challenges.",
    "A long-standing goal will see progress. Keep your focus and determination strong to achieve it.",
    "You will experience a renewed sense of purpose. Let this motivation drive you towards your aspirations.",
    "A meaningful connection will deepen. Nurture this relationship and cherish the bond you share.",
    "You may find yourself reflecting on past experiences. Use these insights to guide your future decisions.",
    "A new perspective will help you solve a problem. Embrace this fresh outlook and find innovative solutions.",
    "You will encounter a situation that requires patience. Trust the process and remain calm.",
    "Your creativity will lead to exciting new opportunities. Explore your artistic side and see where it takes you.",
    "A financial opportunity may arise. Evaluate it carefully and consider how it aligns with your goals.",
    "You will experience a sense of fulfillment from your efforts. Enjoy the rewards of your hard work.",
    "An important relationship will be strengthened. Invest time and energy into nurturing this bond.",
    "You may receive valuable advice from someone you respect. Listen carefully and apply their insights.",
    "Your personal growth will be noticeable. Celebrate your progress and continue to strive for improvement.",
    "A challenge you’ve been facing will resolve itself. Trust in the process and stay positive.",
    "You will find joy in connecting with others. Engage in meaningful conversations and activities.",
    "A new venture or project will spark your interest. Dive into it with enthusiasm and curiosity.",
    "You may discover a hidden talent or skill. Embrace this newfound ability and use it to your advantage.",
    "Your determination will help you achieve your goals. Keep pushing forward and stay focused on your objectives.",
    "An unexpected event will bring excitement into your life. Embrace the change and enjoy the adventure.",
    "You will experience a sense of inner peace. Use this calmness to reflect and plan for the future.",
    "A heartfelt conversation will bring you closer to someone. Open up and share your thoughts and feelings.",
    "Your hard work will pay off in unexpected ways. Stay committed and be ready for the rewards.",
    "A new relationship or connection will bring joy. Nurture this bond and appreciate the new energy it brings.",
    "You may need to take a step back and reassess your priorities. Use this time for reflection and realignment.",
    "Your creativity will lead to a successful project. Channel your ideas and watch them come to life.",
    "A significant change is on the horizon. Embrace it with an open mind and a positive attitude.",
    "You will find clarity in a confusing situation. Trust your intuition and move forward with confidence.",
    "A surprise encounter will bring joy and inspiration. Be open to new connections and experiences.",
    "You may need to let go of something that’s been holding you back. Embrace the freedom and move forward.",
    "Your enthusiasm will inspire others. Share your passion and watch it create positive change.",
    "A sense of accomplishment will boost your confidence. Celebrate your achievements and set new goals.",
    "You will find support in unexpected places. Be open to receiving help and guidance from others.",
    "A personal breakthrough is on the way. Stay focused and be ready to seize new opportunities.",
    "You may experience a surge of creativity. Use this energy to work on projects and explore new ideas.",
    "A new beginning is on the horizon. Embrace the fresh start with optimism and excitement.",
    "You will find joy in the little things today. Appreciate the simple pleasures and find happiness in them.",
    "An important realization will provide clarity. Use this insight to make informed decisions and move forward.",
    "You may need to adapt to changing circumstances. Flexibility and resilience will help you navigate any challenges.",
    "Your efforts will be recognized and rewarded. Enjoy the acknowledgment and continue to strive for excellence.",
    "A meaningful connection will bring comfort and support. Cherish this relationship and the positive impact it has.",
    "You will experience a renewed sense of energy. Use this vitality to pursue your passions and achieve your goals.",
    "A surprising opportunity will present itself. Stay alert and be ready to embrace it with enthusiasm.",
    "You may need to take some time for self-care. Prioritize your well-being and find balance in your life.",
    "Your optimism will attract positive outcomes. Maintain a positive outlook and watch good things come your way.",
    "A creative project will come to fruition. Celebrate your success and continue to explore your creative side.",
    "You will find solace in familiar routines. Use these moments of stability to reflect and recharge.",
    "A new perspective will help you solve a problem. Embrace this fresh outlook and find innovative solutions."
]


yemek_mesaj = [
    "Spaghetti Carbonara",
    "Beef Stroganoff",
    "Chicken Alfredo",
    "Vegetable Stir-Fry",
    "Pork Schnitzel",
    "Lamb Curry",
    "Fish Tacos",
    "Margherita Pizza",
    "Chicken Caesar Salad",
    "Beef Wellington",
    "Shrimp Scampi",
    "Stuffed Bell Peppers",
    "Eggplant Parmesan",
    "Chicken Tikka Masala",
    "Thai Green Curry",
    "Barbecue Ribs",
    "Moussaka",
    "Lasagna",
    "Chicken Pot Pie",
    "Pancakes",
    "Beef Burritos",
    "Pad Thai",
    "Grilled Cheese Sandwich",
    "Fettuccine Alfredo",
    "Chili Con Carne",
    "Vegetable Soup",
    "Clam Chowder",
    "Greek Salad",
    "Pulled Pork Sandwich",
    "Chicken Noodle Soup",
    "Tandoori Chicken",
    "Bangers and Mash",
    "Lobster Roll",
    "Cobb Salad",
    "Baked Ziti",
    "Sweet and Sour Chicken",
    "Ratatouille",
    "Chicken and Waffles",
    "Sushi",
    "Beef Tacos",
    "Falafel",
    "Beef Stroganoff",
    "Crispy Duck",
    "Caesar Wrap",
    "Goulash",
    "Pita Bread with Hummus",
    "Sauerbraten",
    "Minestrone Soup",
    "Jambalaya",
    "Pork Belly",
    "Buffalo Wings",
    "Tortilla Española",
    "Currywurst",
    "Fish and Chips",
    "Baked Macaroni and Cheese",
    "Peking Duck",
    "Tom Yum Soup",
    "Risotto",
    "Shepherd’s Pie",
    "Ramen",
    "Beef Kabobs",
    "Grilled Salmon",
    "Chicken Parmesan",
    "Quiche Lorraine",
    "Pasta Primavera",
    "Maki Rolls",
    "Bangers and Mash",
    "Pork Tenderloin",
    "Chicken Satay",
    "Beef Bourguignon",
    "Egg Drop Soup",
    "BBQ Chicken",
    "Vegetarian Chili",
    "Chicken Kiev",
    "Pad Krapow",
    "Ratatouille",
    "Gnocchi",
    "Tacos al Pastor",
    "Eggs Benedict",
    "Lentil Soup",
    "Cornbread",
    "Osso Buco",
    "Hummus and Pita",
    "Clam Bake",
    "Jollof Rice",
    "Beef and Broccoli Stir-Fry",
    "Pasta Carbonara",
    "Crab Cakes",
    "Beef Enchiladas",
    "Chicken Adobo",
    "Chicken Curry",
    "Pulled Pork Tacos",
    "Salmon Teriyaki",
    "Biryani",
    "French Onion Soup",
    "Vegetarian Lasagna",
    "BBQ Ribs",
    "Duck Confit",
    "Stuffed Mushrooms",
    "Lamb Shank",
    "Goulash",
    "Scallops",
    "Chow Mein",
    "Vegetable Frittata",
    "Ceviche",
    "Cheeseburger",
    "Duck à l'Orange",
    "Risotto Milanese",
    "Tomato Basil Soup",
    "Tandoori Lamb Chops",
    "Moussaka",
    "Pork Ramen",
    "Grilled Shrimp",
    "Seafood Paella",
    "Chickpea Salad",
    "Cheese Fondue",
    "Teriyaki Chicken",
    "Pork Chop",
    "Butternut Squash Soup",
    "Crispy Chicken Sandwich",
    "Pumpkin Soup",
    "Eggplant Rollatini",
    "Sweet Potato Fries",
    "Tacos de Carnitas",
    "Mango Salsa",
    "Crème Brûlée",
    "Pasta Puttanesca",
    "Lamb Gyro",
    "Corn Chowder",
    "Chicken Fajitas",
    "Pancetta Wrapped Scallops",
    "Fish Curry",
    "Chicken Katsu",
    "Black Bean Soup",
    "Falafel Wrap",
    "Spicy Tuna Roll",
    "Beef Meatballs",
    "Chicken Piccata",
    "Pasta Bolognese",
    "Braised Short Ribs",
    "Eggplant and Tomato Stew",
    "Lamb Kofta",
    "Hot Pot",
    "Fried Rice",
    "Chicken and Rice Casserole",
    "Jerk Chicken",
    "Moroccan Tagine",
    "Korean BBQ",
    "Chicken Empanadas",
    "Beef Meatloaf",
    "Crab Rangoon",
    "Chickpea Curry",
    "Spinach Artichoke Dip",
    "Crispy Calamari",
    "Lobster Bisque",
    "Roast Beef",
    "Spaghetti Bolognese",
    "Chicken Sausage",
    "Zucchini Bread",
    "Lentil Curry",
    "Barbecue Chicken Wings",
    "Tomato Bruschetta",
    "Chana Masala",
    "Seafood Chowder",
    "Chicken Caesar Wrap",
    "Tandoori Chicken Wings",
    "Vegetable Curry",
    "Coconut Shrimp",
    "Szechuan Noodles",
    "Pasta Salad",
    "Sweet Corn Soup",
    "Pasta with Pesto",
    "Beef Tenderloin",
    "Lamb Chops",
    "Vegetable Samosas",
    "Lemon Chicken",
    "Pork Ribs",
    "Butternut Squash Risotto",
    "Vegetarian Sushi",
    "Grilled Tuna Steak",
    "Philly Cheesesteak",
    "Chicken Shawarma",
    "Omelette",
    "Pork BBQ",
    "Clam Linguine",
    "Eggplant Curry",
    "Chicken Quesadilla",
    "Seafood Risotto",
    "Spaghetti with Meatballs",
    "Buffalo Chicken Dip",
    "Mango Chicken Salad",
    "Crepes",
    "Pulled Pork Sandwich",
    "Shrimp and Grits",
    "Grilled Veggie Skewers",
    "Cheesesteak",
    "Beef Wellington",
    "Cabbage Rolls",
    "Chicken Marsala",
    "Roasted Vegetables",
    "Egg Salad Sandwich",
    "Stuffed Cabbage",
    "Lentil Stew",
    "Chicken and Rice Soup",
    "Avocado Toast",
    "Beef Shank",
    "Buffalo Cauliflower",
    "Salmon Patties",
    "Pasta Alfredo",
    "Chicken and Mushroom Pie",
    "Creamy Tomato Soup",
    "Vegetable Korma",
    "Mediterranean Salad",
    "Beef Nachos",
    "Pasta Salad with Tuna",
    "Sweet Potato Hash",
    "Fish Stew",
    "Buttermilk Fried Chicken",
    "Chicken Fried Rice",
    "Baked Potatoes",
    "Beef Quesadillas",
    "Vegetable Tempura",
    "Lamb Curry with Rice",
    "Spicy Chicken Wings",
    "Tortilla Soup",
    "Grilled Chicken Salad",
    "Mushroom Risotto",
    "Bulgur Pilaf",
    "Chicken Tortilla Soup",
    "Turkey Meatballs",
    "Stuffed Zucchini",
    "Pork Schnitzel with Mashed Potatoes",
    "Vegetarian Enchiladas",
    "Chicken Cacciatore",
    "Lamb Saag",
    "Vegetarian Chili",
    "Garlic Shrimp",
    "Pasta with Meat Sauce",
    "Vegetable Fried Rice",
    "Chicken Burritos",
    "Spicy Beef Tacos",
    "Chicken Teriyaki Bowl",
    "Roasted Chicken",
    "Fish Tacos with Slaw",
    "Spaghetti Puttanesca",
    "Kale Salad",
    "Cabbage Soup",
    "Pork Carnitas",
    "Smashed Potatoes",
    "Thai Red Curry",
    "Braised Lamb Shanks",
    "Tomato Basil Pasta",
    "Beef Stroganoff with Egg Noodles",
    "Mushroom Stroganoff",
    "Stuffed Acorn Squash",
    "Beef Kebab",
    "Chicken Jalfrezi",
    "Spinach Quiche",
    "Pasta with Marinara Sauce",
    "Salmon and Asparagus",
    "Chicken Fettuccine",
    "Vegetable Lasagna",
    "Blackened Fish",
    "Pasta Primavera with Shrimp",
    "Basil Chicken",
    "Cheese Ravioli",
    "Chicken Fricassée",
    "Grilled Pork Chops",
    "Spicy Lentil Soup",
    "Beef Korma",
    "Chicken Fajitas with Peppers",
    "Pasta with Garlic and Oil",
    "Vegetarian Stuffed Peppers",
    "Chicken Pot Pie with Biscuits",
    "Mango Chicken Curry",
    "Pork Chops with Apples",
    "Beef Chili",
    "Chicken Scallopini",
    "Stuffed Bell Peppers with Rice",
    "Lentil Soup with Ham",
    "Chicken Gyro",
    "Beef Burrito Bowl",
    "Vegetarian Burritos",
    "Fried Green Tomatoes",
    "Seafood Gumbo",
    "Baked Eggplant Parmesan"
]
